# Generated by Django 4.1.7 on 2023-03-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_remove_menuitem_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
